#version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-db
    image: sanket9877/vprofiledb
    container_name: vprodb  
    ports:
      - "3306:3306"
    volumes: 
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass 
  redis:
    image: "redis:alpine"

  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest  

  vproapp:
    build: 
      context: ./Docker-app
    image: sanket9877/vprofileapp
    container_name: vproapp  
    ports:
      - "8000:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps
   
  vproweb:
    build: 
      context: ./Docker-web
    image: sanket9877/vprofileweb
    container_name: vproweb  
    ports:
      - "8008:80" 

volumes:
  vprodbdata: {}
  vproappdata: {}